### ISSUE TITLE
only allow super call in class constructor

### ISSUE THREAD

**Issue by hax** [army8735/jsdc#25]
```js
class Test {
  method() {
    super()  // <- should throw syntax error here
  }
}
```
It should also apply to normal functions or generators.

See `HasDirectSuper` static semantics in the draft.

**Comment by army8735** [comment]
ok

**Comment by army8735** [comment]
这应该是解析时异常，还是运行时异常。
貌似运行时也无法报……
应该在依赖的homunculus里做了

**Comment by hax** [comment]
应该是 early error，对于transpiler来说应该是编译时错误。
